version: 1

update_configs:
    - package_manager: "javascript"
      directory: "/"
      update_schedule: "weekly"
      default_labels:
          - "patch"
      default_reviewers:
          - "mhlz"
          - "reckter"
          - "LionC"
          - "samihamed"

