name: Setup repository

on:
  push: 
    branches:
      - master

jobs:
  setup:
    name: Setup
    if: "contains(github.ref, 'master')"
    runs-on: ubuntu-latest
    steps:
        - run: echo ${{github.GITHUB_REF}}
        - run: |
            if [[ -z "$GITHUB_BOT_TOKEN" ]]; then 
              echo "Please set the GITHUB_BOT_TOKEN (from 1Password) in the repository secret settings!"
              exit -1
            fi
          env:
            GITHUB_BOT_TOKEN: ${{ secrets.GITHUB_BOT_TOKEN }}
        - uses: actions/checkout@v1
        - name: Prepare repository
          run: |
            git checkout master --
            git remote rm origin
            git remote add origin https://homefully-bot:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
            git fetch origin --tags
            git branch --set-upstream-to origin/master master
          env:
            GITHUB_TOKEN: ${{secrets.GITHUB_BOT_TOKEN}}
        - uses: actions/setup-node@v1
        - run: cat package.json | jq ".name=\"@$GITHUB_REPOSITORY\"" | jq ".repository.url=\"github:$GITHUB_REPOSITORY\"" > package2.json
        - run: mv package2.json package.json
        - run: npm i
        - run: rm .github/workflows/create.yml
        - run: git add .
        - run: |
            git config --global user.email "setup.github@homefully.de"
            git config --global user.name "github actions"
        - run: git commit -m ":tada:"
        - run: npx auto create-labels
          env:
            GH_TOKEN: ${{ secrets.GITHUB_BOT_TOKEN }}
            NPM_TOKEN: ${{ secrets.GITHUB_BOT_TOKEN }}
        - run: npx auto shipit
          env:
            GH_TOKEN: ${{ secrets.GITHUB_BOT_TOKEN }}
            NPM_TOKEN: ${{ secrets.GITHUB_BOT_TOKEN }}
            NODE_AUTH_TOKEN: ${{secrets.GITHUB_BOT_TOKEN}}
