name: On Push

on: [ push ]

jobs:
    audit:
        name: Audit
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master
            -   uses: actions/setup-node@master
                with:
                    node-version: 12
                    registry-url: 'https://registry.npmjs.org'
            -   run: npm audit
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master
            -   uses: actions/setup-node@master
                with:
                    node-version: 12
                    registry-url: https://npm.pkg.github.com
                    scope: '@homefully'
                    always-auth: true
                env:
                    NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
            -   uses: actions/cache@v1
                id: cache-modules
                with:
                    path: node_modules
                    key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
            -   uses: actions/cache@v1
                if: steps.cache-modules.outputs.cache-hit != 'true'
                with:
                    path: ~/.npm
                    key: ${{ runner.os }}-node-global
            -   run: npm ci
                if: steps.cache-modules.outputs.cache-hit != 'true'
                env:
                    NODE_AUTH_TOKEN: ${{secrets.GITHUB_BOT_TOKEN}}
            -   run: npm run lint
            -   run: npm run test:ci
            -   run: npm run build

    publish-gpr:
        needs: test
        runs-on: ubuntu-latest
        if: "contains(github.ref, 'master') && !contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
        steps:
            -   uses: actions/checkout@v1
            -   name: Prepare repository
                run: |
                    git checkout ${GITHUB_REF##*/} --
                    git remote rm origin
                    git remote add origin https://homefully-bot:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
                    git fetch origin --tags
                    git branch --set-upstream-to origin/${GITHUB_REF##*/} ${GITHUB_REF##*/}
                env:
                    GITHUB_TOKEN: ${{secrets.GITHUB_BOT_TOKEN}}
            -   uses: actions/setup-node@v1
                with:
                    node-version: 12
                    registry-url: https://npm.pkg.github.com/
                    always-auth: true
                    scope: '@homefully'
                env:
                    NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
            -   uses: actions/cache@v1
                id: cache-modules
                with:
                    path: node_modules
                    key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
            -   uses: actions/cache@v1
                if: steps.cache-modules.outputs.cache-hit != 'true'
                with:
                    path: ~/.npm
                    key: ${{ runner.os }}-node-global
            -   run: npm ci
                if: steps.cache-modules.outputs.cache-hit != 'true'
                env:
                    NODE_AUTH_TOKEN: ${{secrets.GITHUB_BOT_TOKEN}}
            -   run: npm run build
            -   run: npx auto shipit
                env:
                    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}


