name: Release new Version

on:
  push:
    branches:
      - "master"
    tags-ignore:
      - "v*"

jobs:
  release-new-version:
    name: Release new version
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@main
        with:
          token: ${{secrets.PUBLIC_GH_BOT_TOKEN}}
      - run: git fetch --prune --unshallow
      - uses: actions/setup-node@main
        with:
          node-version: 14
      - uses: actions/cache@main
        id: cache-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/cache@main
        if: steps.cache-modules.outputs.cache-hit != 'true'
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-global
      - run: npm ci
        if: steps.cache-modules.outputs.cache-hit != 'true'
      - run: npm run build
      - run: git config --global user.email "bot@homefully.de"
      - run: git config --global user.name "homefully bot"
      - run: npx auto shipit
        env:
          GH_TOKEN: ${{ secrets.PUBLIC_GH_BOT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
